// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestSekolah.Data;

#nullable disable

namespace RestSekolah.Migrations
{
    [DbContext(typeof(SekolahDbContext))]
    partial class SekolahDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RestSekolah.Models.JadwaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hari")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Jam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kelas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MataPelajaran")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pengajar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("jadwal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hari = "Senin",
                            Jam = "08:00 - 09:30",
                            Kelas = "XII IPA 1",
                            MataPelajaran = "Matematika",
                            Pengajar = "Budi"
                        },
                        new
                        {
                            Id = 2,
                            Hari = "Selasa",
                            Jam = "10:00 - 11:30",
                            Kelas = "XII IPS 2",
                            MataPelajaran = "Bahasa Inggris",
                            Pengajar = "Siti"
                        },
                        new
                        {
                            Id = 3,
                            Hari = "Rabu",
                            Jam = "08:00 - 09:30",
                            Kelas = "XII IPA 1",
                            MataPelajaran = "Biologi",
                            Pengajar = "Andi"
                        },
                        new
                        {
                            Id = 4,
                            Hari = "Kamis",
                            Jam = "10:00 - 11:30",
                            Kelas = "XII IPS 2",
                            MataPelajaran = "Ekonomi",
                            Pengajar = "Dewi"
                        },
                        new
                        {
                            Id = 5,
                            Hari = "Jumat",
                            Jam = "08:00 - 09:30",
                            Kelas = "XII IPA 1",
                            MataPelajaran = "Kimia",
                            Pengajar = "Rudi"
                        },
                        new
                        {
                            Id = 6,
                            Hari = "Sabtu",
                            Jam = "10:00 - 11:30",
                            Kelas = "XII IPS 2",
                            MataPelajaran = "Geografi",
                            Pengajar = "Ani"
                        },
                        new
                        {
                            Id = 7,
                            Hari = "Minggu",
                            Jam = "08:00 - 09:30",
                            Kelas = "XII IPA 1",
                            MataPelajaran = "Fisika",
                            Pengajar = "Budi"
                        },
                        new
                        {
                            Id = 8,
                            Hari = "Senin",
                            Jam = "10:00 - 11:30",
                            Kelas = "XII IPS 2",
                            MataPelajaran = "Sosiologi",
                            Pengajar = "Siti"
                        });
                });

            modelBuilder.Entity("RestSekolah.Models.KelasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JumlahSiswa")
                        .HasColumnType("int");

                    b.Property<string>("Jurusan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("int");

                    b.Property<string>("NamaKelas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("kelas");
                });

            modelBuilder.Entity("RestSekolah.Models.MapelModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("JumlahSiswa")
                        .HasColumnType("int");

                    b.Property<string>("Kelas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("mapel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Jenis = "Wajib",
                            JumlahSiswa = 30,
                            Kelas = "XII IPA 1",
                            Keterangan = "Matematika Dasar",
                            Kode = "MTH101",
                            Nama = "Matematika",
                            Semester = "Ganjil"
                        },
                        new
                        {
                            Id = 2,
                            Jenis = "Wajib",
                            JumlahSiswa = 25,
                            Kelas = "XII IPS 2",
                            Keterangan = "Bahasa Inggris Dasar",
                            Kode = "ENG101",
                            Nama = "Bahasa Inggris",
                            Semester = "Genap"
                        },
                        new
                        {
                            Id = 3,
                            Jenis = "Wajib",
                            JumlahSiswa = 30,
                            Kelas = "XII IPA 1",
                            Keterangan = "Biologi Dasar",
                            Kode = "BIO101",
                            Nama = "Biologi",
                            Semester = "Ganjil"
                        },
                        new
                        {
                            Id = 4,
                            Jenis = "Wajib",
                            JumlahSiswa = 25,
                            Kelas = "XII IPS 2",
                            Keterangan = "Ekonomi Dasar",
                            Kode = "EKO101",
                            Nama = "Ekonomi",
                            Semester = "Genap"
                        },
                        new
                        {
                            Id = 5,
                            Jenis = "Wajib",
                            JumlahSiswa = 30,
                            Kelas = "XII IPA 1",
                            Keterangan = "Kimia Dasar",
                            Kode = "KIM101",
                            Nama = "Kimia",
                            Semester = "Ganjil"
                        },
                        new
                        {
                            Id = 6,
                            Jenis = "Wajib",
                            JumlahSiswa = 25,
                            Kelas = "XII IPS 2",
                            Keterangan = "Geografi Dasar",
                            Kode = "GEO101",
                            Nama = "Geografi",
                            Semester = "Genap"
                        },
                        new
                        {
                            Id = 7,
                            Jenis = "Wajib",
                            JumlahSiswa = 30,
                            Kelas = "XII IPA 1",
                            Keterangan = "Fisika Dasar",
                            Kode = "FIS101",
                            Nama = "Fisika",
                            Semester = "Ganjil"
                        },
                        new
                        {
                            Id = 8,
                            Jenis = "Wajib",
                            JumlahSiswa = 25,
                            Kelas = "XII IPS 2",
                            Keterangan = "Sosiologi Dasar",
                            Kode = "SOS101",
                            Nama = "Sosiologi",
                            Semester = "Genap"
                        },
                        new
                        {
                            Id = 9,
                            Jenis = "Wajib",
                            JumlahSiswa = 30,
                            Kelas = "XII IPA 1",
                            Keterangan = "Sejarah Dasar",
                            Kode = "SEJ101",
                            Nama = "Sejarah",
                            Semester = "Ganjil"
                        },
                        new
                        {
                            Id = 10,
                            Jenis = "Wajib",
                            JumlahSiswa = 25,
                            Kelas = "XII IPS 2",
                            Keterangan = "Pendidikan Agama Dasar",
                            Kode = "AGM101",
                            Nama = "Pendidikan Agama",
                            Semester = "Genap"
                        },
                        new
                        {
                            Id = 11,
                            Jenis = "Wajib",
                            JumlahSiswa = 30,
                            Kelas = "XII IPA 1",
                            Keterangan = "Pendidikan Pancasila Dasar",
                            Kode = "PPKN101",
                            Nama = "Pendidikan Pancasila",
                            Semester = "Ganjil"
                        },
                        new
                        {
                            Id = 12,
                            Jenis = "Wajib",
                            JumlahSiswa = 25,
                            Kelas = "XII IPS 2",
                            Keterangan = "Kewirausahaan Dasar",
                            Kode = "KWR101",
                            Nama = "Kewirausahaan",
                            Semester = "Genap"
                        },
                        new
                        {
                            Id = 13,
                            Jenis = "Wajib",
                            JumlahSiswa = 30,
                            Kelas = "XII IPA 1",
                            Keterangan = "Seni Budaya Dasar",
                            Kode = "SEN101",
                            Nama = "Seni Budaya",
                            Semester = "Ganjil"
                        },
                        new
                        {
                            Id = 14,
                            Jenis = "Wajib",
                            JumlahSiswa = 25,
                            Kelas = "XII IPS 2",
                            Keterangan = "Olahraga Dasar",
                            Kode = "OLR101",
                            Nama = "Olahraga",
                            Semester = "Genap"
                        },
                        new
                        {
                            Id = 15,
                            Jenis = "Wajib",
                            JumlahSiswa = 30,
                            Kelas = "XII IPA 1",
                            Keterangan = "Bahasa Indonesia Dasar",
                            Kode = "IND101",
                            Nama = "Bahasa Indonesia",
                            Semester = "Ganjil"
                        },
                        new
                        {
                            Id = 16,
                            Jenis = "Wajib",
                            JumlahSiswa = 25,
                            Kelas = "XII IPS 2",
                            Keterangan = "Bahasa Jepang Dasar",
                            Kode = "JPN101",
                            Nama = "Bahasa Jepang",
                            Semester = "Genap"
                        },
                        new
                        {
                            Id = 17,
                            Jenis = "Wajib",
                            JumlahSiswa = 30,
                            Kelas = "XII IPA 1",
                            Keterangan = "Bahasa Mandarin Dasar",
                            Kode = "MND101",
                            Nama = "Bahasa Mandarin",
                            Semester = "Ganjil"
                        },
                        new
                        {
                            Id = 18,
                            Jenis = "Wajib",
                            JumlahSiswa = 25,
                            Kelas = "XII IPS 2",
                            Keterangan = "Bahasa Perancis Dasar",
                            Kode = "FRN101",
                            Nama = "Bahasa Perancis",
                            Semester = "Genap"
                        },
                        new
                        {
                            Id = 19,
                            Jenis = "Wajib",
                            JumlahSiswa = 30,
                            Kelas = "XII IPA 1",
                            Keterangan = "Bahasa Arab Dasar",
                            Kode = "ARB101",
                            Nama = "Bahasa Arab",
                            Semester = "Ganjil"
                        },
                        new
                        {
                            Id = 20,
                            Jenis = "Wajib",
                            JumlahSiswa = 25,
                            Kelas = "XII IPS 2",
                            Keterangan = "Bahasa Jerman Dasar",
                            Kode = "GRM101",
                            Nama = "Bahasa Jerman",
                            Semester = "Genap"
                        },
                        new
                        {
                            Id = 21,
                            Jenis = "Wajib",
                            JumlahSiswa = 30,
                            Kelas = "XII IPA 1",
                            Keterangan = "Bahasa Korea Dasar",
                            Kode = "KOR101",
                            Nama = "Bahasa Korea",
                            Semester = "Ganjil"
                        },
                        new
                        {
                            Id = 22,
                            Jenis = "Wajib",
                            JumlahSiswa = 25,
                            Kelas = "XII IPS 2",
                            Keterangan = "Bahasa Rusia Dasar",
                            Kode = "RUS101",
                            Nama = "Bahasa Rusia",
                            Semester = "Genap"
                        },
                        new
                        {
                            Id = 23,
                            Jenis = "Wajib",
                            JumlahSiswa = 30,
                            Kelas = "XII IPA 1",
                            Keterangan = "Bahasa Spanyol Dasar",
                            Kode = "SPN101",
                            Nama = "Bahasa Spanyol",
                            Semester = "Ganjil"
                        },
                        new
                        {
                            Id = 24,
                            Jenis = "Wajib",
                            JumlahSiswa = 25,
                            Kelas = "XII IPS 2",
                            Keterangan = "Bahasa Italia Dasar",
                            Kode = "ITA101",
                            Nama = "Bahasa Italia",
                            Semester = "Genap"
                        });
                });

            modelBuilder.Entity("RestSekolah.Models.SiswaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kelas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoTelp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("siswa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alamat = "Padang",
                            Kelas = "XII IPA 1",
                            Nama = "Ismarianto",
                            NoTelp = "081234567890"
                        },
                        new
                        {
                            Id = 2,
                            Alamat = "Jakarta",
                            Kelas = "XII IPS 2",
                            Nama = "Amalya",
                            NoTelp = "089876543210"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
